# Node.js
# Build a general Node.js project with yarn.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "vs2017-win2016"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "8.x"
    displayName: "Install Node.js"

  - script: yarn bootstrap

  - script: yarn test
    env:
      GENERATE_JEST_REPORT: true

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: "**junit*.xml"
      testRunTitle: TestRun ${{ parameters.name }} $(node_version)

  - task: PublishCodeCoverageResults@1
    displayName: "Publish code coverage results"
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: "cobertura"
      summaryFileLocation: "**/coverage/cobertura-coverage.xml"
